### ISSUE TITLE
Error Page Handler first real resource look-up fails with etc maps

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1415]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.x
* [X] ACS AEM Commons Version: 3.x
* [X] Reproducible on Latest? yes

Via @jochen314 

 don't get it: We already have resolved the url to a resource path.
Now we check for the parent.
Why do we need to do a resolve with the request and not just a getResource?

> For us, this does not work:
> We have multiple vhosts on the same instance. So out /etc/map maps:
> http://host1/ -> /content/host1 and
> http://host2/ -> /content/host2
> When the url http//host1/en/not-existing.html:
> the Url get mapped to the NonExistingResource /content/host1/en/not-existing
> At this line, candidatePath is /content/host1/en
> And this gets resolved to /content/host1/content/host1/en, which is not, want we need.
> 
> We need to either:
> 
> * walk up the URL and resolve on each stop or
> * walk up the resolved path and then got a getResource
> Currently is seems to be mixed up

https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/aab03112d399fc81eb031b5426602db4e12be1a2#diff-730590a3bca3e92d4ed6242cf2e510a5

**Comment by davidjgonzalez** [comment]
Fixed in 3.17.2

**Comment by jochen314** [comment]
Hi,

sorry to bother, but my problem is not fixed.

My problem is in the `for` loop (line 560):
`for (int i = parts.length - 1; i >= 0; i--) {`

`parts` is 

> [content, test, www, global, de, errors, 40dddddd4]

(/content/test/ww/global/de exists)

But as there is a resolve with request, the existing resource is not found. The mapping added another /content/test/www in front.
