### ISSUE TITLE
Draggable Lists' interface is broken

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1842]
* [ ] AEM Version: `6.5`
* [ ] ACS AEM Commons Version: `4.0.0`
* [ ] Reproducible on Latest? yes

### Expected Behavior

The [Draggable Lists](https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/draggable-list/index.html)' interface allows to order its elements.

### Actual Behavior

The [Draggable Lists](https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/draggable-list/index.html)' interface is broken:

![incorrect-draggable](https://user-images.githubusercontent.com/5563546/56286960-651e3300-611b-11e9-88b0-85ebb4710e16.png)

It does not allow the dragging behaviour either.

### Steps to Reproduce

Follow steps from the [docs](https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/draggable-list/index.html).

**Comment by davidjgonzalez** [comment]
@justinedelson for some reason I had it in my head this was generic lists, my bad

**Comment by reggie7** [comment]
After retest with latest code - it works properly in `6.5`. I am not sure if something got fixed or it's just me who has configured everything properly this time, but anyway it's working just fine:

![fixed](https://user-images.githubusercontent.com/5563546/56894407-10b57480-6a86-11e9-9f4b-b935b8c1a81f.png)

**Comment by johnvlach** [comment]
commenting here since I don't want to create a duplicate:

For me the issue persists even if i use acs-aem-commons 4.8.4 with AEM 6.5.5 and 6.5.6. I cannot drag and reorder items in draggablelist for an any experience fragment that I have created and hosts a draggablelist instance. Note that exactly the same content in AEM 6.3.3 does not manifest this issue 
Not sure what @reggie7  meant with the latest code.
Could you please provide any pointers for this?

**Comment by vixenaga** [comment]
Hi, I have this issue with wrong styling even after installing acs commons version 5.0.4 on aem 6.5. Do you know what could be a problem here?

**Comment by vixenaga** [comment]
To fix this problem css.txt should not be empty, you have to put into css.txt the following line:
/apps/acs-commons/touchui-widgets/draggable-list/source/draggablelist.css

**Comment by davidjgonzalez** [comment]
@vixenaga  this should be fixed (the css.txt points to the draggablelist.css)

![2021-09-07 at 9 11 AM](https://user-images.githubusercontent.com/1451868/132350651-743e1ef8-49ff-49c4-8e14-79ae01afa9d7.jpg)


@johnvlach  I think you're probably missing your custom cq:clientLibraryFolder definition that proxies these CSS/JS in ... You need to create something like 

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    jcr:primaryType="cq:ClientLibraryFolder"
          jsProcessor="[default:none,min:gcc]"
          allowProxy="{Boolean}true"
          categories="[cq.authoring.dialog,granite.ui.coral.foundation.addon.coral2]"
          embed="[acs-commons.widgets.draggable-list]"/>
```

in your project (or do the granite:extraClientLIbs -- or whatever that property is -- in your dialog for category: cs-commons.widgets.draggable-list)
