### ISSUE TITLE
GenericList.getItems() does not return any list item having null value.

### ISSUE THREAD

**Issue by sagarmandal** [Adobe-Consulting-Services/acs-aem-commons#2248]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.3.0
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? yes (based on code)

### Expected Behavior
GenericList.getItems() should return any item having null value similar to .../_jcr_content.list.json.
This will make it consistent as well as useful, where user may want to add an item having null value.
e.g., Dropdown Option as "Select" or "None". This dropdown option can be used to remove the previously selected value, if required.

### Actual Behavior

GenericList.getItems() does not return any item having null value.
Whereas .../_jcr_content.list.json on the list page returns all items including item having null value.

### Steps to Reproduce

1. Create a Generic List
2. Add multiple items, including one or more item having null value but with title (e.g., "None") 
3. Access the list page path suffixed with /_jcr_content.list.json. This will provide all items having non-null title.
4. Write Java code to use Generic List API. e..g,
    PageManager pageManager = resourceResolver.adaptTo(PageManager.class);
    Page listPage = pageManager.getPage("/etc/acs-commons/lists/targets"); // e.g., /etc/acs-commons/lists/targets is our list
    GenericList list = listPage.adaptTo(GenericList.class);

    ///Check output of list.getItems();

### Links

NA

**Comment by davidjgonzalez** [comment]
Fixed in v4.5.2

**Comment by prasanna9936** [comment]
Hi David, i'm still having the same issue with latest acs commons package- 4.11.2. I see a blank screen in UI and the below error in logs: org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource JcrNodeResource, type=acs-commons/components/utilities/genericlist, superType=null,

**Comment by davidjgonzalez** [comment]
Was this expected to be fixed in 4.11.2?

**Comment by prasanna9936** [comment]
I see it got fixed based of the release notes in 4.11.2
https://raw.githubusercontent.com/Adobe-Consulting-Services/acs-aem-commons/master/CHANGELOG.md

**Comment by davidjgonzalez** [comment]
The shaded guava or the versioned clientlibs ? Those are the only 2 items
in 4.11.2, no?

**Comment by prasanna9936** [comment]
There is a full list in this link, https://raw.githubusercontent.com/Adobe-Consulting-Services/acs-aem-commons/master/CHANGELOG.md and search for #2248.

**Comment by davidjgonzalez** [comment]
Oh - that was (allegedly) fixed back in 4.5.2 (last April).. maybe something regressed that fix since then ..?

**Comment by prasanna9936** [comment]
Yeah looks like it. Because that link has more than 100+ defects which can't be addressed in one release .

**Comment by davidjgonzalez** [comment]
Correct. The change log is a running list of changer per release. Each release has a section in the chnagelog, newest at the top. Top of the chnagelog has a link to a web site that explains the format.

But I guess the important thing is the bug still exists and we need to be fixed :)

**Comment by prasanna9936** [comment]
Yeah the bug exists, i'm more than happy to try any other ideas to isolate the problem to ACS. Let me know if you need some help in reproducing the issue.

**Comment by davidjgonzalez** [comment]
This is with 5.3.2 installed: 

![2022-07-27 at 4 47 PM](https://user-images.githubusercontent.com/1451868/181369234-fa53eee5-a12f-4488-ba26-a16cf05c73bf.png)

![2022-07-27 at 4 47 PM](https://user-images.githubusercontent.com/1451868/181369259-88f9268a-2a66-4ade-8f9e-c97f01c62b9a.png)
