### ISSUE TITLE
Error while executing Page Report with "All Results" selected

### ISSUE THREAD

**Issue by ivanarizovski** [Adobe-Consulting-Services/acs-aem-commons#2449]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6.0
* [ ] ACS AEM Commons Version: 4.5.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
Show all results on the page. 

### Actual Behavior
Only 200-300 (out of 5000) results are displayed and the following error is shown:
Exception executing report: org.apache.sling.api.request.TooManyCallsException: /apps/acs-commons/components/utilities/report-builder/columns/date/results.jsp /apps/acs-commons/components/utilities/report-builder/columns/date/results.jsp

### Steps to Reproduce
1. Navigate to the Page Report (Tools -> ACS AEM Commons -> Reports ->Page Report)
2. Enter a page path
3. Select the "All Results" checkbox
4. Click on the "Execute Report" button
5. Scroll down to the last result and check if the number corresponds to the total number of the results that should be displayed

**Comment by badvision** [comment]
Can you reproduce against the latest master branch?  We just fixed an issue with report generation which affects the code in question, hopefully for the better.

**Comment by ivanarizovski** [comment]
@badvision I am still getting the error but on the editor component. See the screenshot:
![image](https://user-images.githubusercontent.com/72967043/96586701-a29be780-12e1-11eb-8ea7-6ff2637ad94c.png)

**Comment by badvision** [comment]
Oh, that's a sling setting preventing too many server-side includes.  You will only be able to download that report, you can't view that online unless you change the number of sling includes allowed in OSGi configuration manager, see here for more information: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/aem-6-2-too-many-calls-sling-exception/qaq-p/224517

**Comment by klcodanr** [comment]
Yes, this is expected behavior.
