### ISSUE TITLE
Replication Status is always rendered as NOT_ACTIVATED when downloading the Report as CSV

### ISSUE THREAD

**Issue by gquintillan** [Adobe-Consulting-Services/acs-aem-commons#2812]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5.12
* [X] ACS AEM Commons Version: 5.0.14
* [X] Reproducible on Latest? yes, tested also in 5.2.0

### Expected Behavior

When downloading a report as CSV the "Replication Status Column" ([documentation](https://adobe-consulting-services.github.io/acs-aem-commons/features/report-builder/configuring.html)) must show the same value than in the HTML rendered report.

### Actual Behavior
When downloading a report as CSV the "Replication Status Column" always shows the status "NOT_ACTIVATED"

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/25983819/161531031-448b0917-18dc-419f-ae4a-ab00ae0eb05f.png">

After debugging the code this is what I found: 
- PageReplicationStatusModel -> getReplicationStatus() ignores the Resource that is passed as a parameter: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/reports/models/PageReplicationStatusModel.java#L104
- Instead it uses the resource that represents the Replication Status Column (the column definition).
- ReplicationStatus is null and the default value "Status.NOT_ACTIVATED" is used.
![image](https://user-images.githubusercontent.com/25983819/161529087-271b5cb4-7ace-4813-8c0f-584044a25da8.png)

### Steps to Reproduce

1. Navigate to ACS Commons Reports: /apps/acs-commons/content/reports.html
2. Open the sample Page Report: /editor.html/var/acs-commons/reports/sample-page-report.html
3. Select the "Path" of a known site, for instance: /content/we-retail (make sure that there are published pages)
5. Click on "Execute Report.
6. Click on "Download Report"
7. Compare the Replication Status Column.

### Links

- Report Builder, Replication Status Column documentation: https://adobe-consulting-services.github.io/acs-aem-commons/features/report-builder/configuring.html
- ReportCSVExportServlet code: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/reports/internal/ReportCSVExportServlet.java#L165
- PageReplicationStatusModel code: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/reports/models/PageReplicationStatusModel.java#L104

**Comment by davidjgonzalez** [comment]
Fixed with https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2820

**Comment by gquintillan** [comment]
> Fixed with #2820

Thank you!

**Comment by davidjgonzalez** [comment]
Fixed in 5.3.0

**Comment by gouli** [comment]
This issue still exists with version 5.3.0 - Can this task be re-opened ?

**Comment by davidjgonzalez** [comment]
Sure - can you PR a fix when you have a moment? Might be helpful to post your AEM version and ACS Commons version as well - since this was fixed before and now seems to have broken again; will be interesting to understand the cause a bit more.
