### ISSUE TITLE
Cloud Manager build  giving error on image/placeholders

### ISSUE THREAD

**Issue by SearchFoundation2022** [Adobe-Consulting-Services/acs-aem-commons#2848]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______AEM as Cloud Service 2022.4.7138.20220427T075748Z
* [ ] ACS AEM Commons Version: 5.2.0
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

Pipeline test should not give ClientlibProxyResource finding as Bug.

### Actual Behavior

When we are running pipeline in cloud service, in build we are getting bugs in ACS-AEM-Commons:

The resource /apps/acs-commons/widgets/source/images/placeholders/**cq-ad-placeholder.png** is contained in a proxy client library /apps/acs-commons/widgets and must be below /apps/acs-commons/widgets/resources to be served correctly on publish.

The resource /apps/acs-commons/widgets/source/images/placeholders/**cq-ul-placeholder.png** is contained in a proxy client library /apps/acs-commons/widgets and must be below /apps/acs-commons/widgets/resources to be served correctly on publish.

The resource /apps/acs-commons/widgets/source/images/placeholders/**cq-audio-placeholder.png** is contained in a proxy client library /apps/acs-commons/widgets and must be below /apps/acs-commons/widgets/resources to be served correctly on publish.

The resource /apps/acs-commons/widgets/source/images/placeholders/**cq-textlines-placeholder.png** is contained in a proxy client library /apps/acs-commons/widgets and must be below /apps/acs-commons/widgets/resources to be served correctly on publish.

The resource /apps/acs-commons/widgets/source/images/placeholders/**cq-dl-placeholder.png** is contained in a proxy client library /apps/acs-commons/widgets and must be below /apps/acs-commons/widgets/resources to be served correctly on publish.

The resource /apps/acs-commons/widgets/themes/default/source/**audio.png** is contained in a proxy client library /apps/acs-commons/widgets/themes/default and must be below /apps/acs-commons/widgets/themes/default/resources to be served correctly on publish.

### Steps to Reproduce

Step1: Use the version 5.2.0 acs common package.
Step2: Run the pipeline.
Step3: In report we are getting these findings. 

### Links

/apps/acs-commons/widgets/themes/default/source/**audio.png** 
 /apps/acs-commons/widgets/source/images/placeholders/**cq-dl-placeholder.png**
 /apps/acs-commons/widgets/source/images/placeholders/**cq-textlines-placeholder.png**
/apps/acs-commons/widgets/source/images/placeholders/**cq-audio-placeholder.png**  
/apps/acs-commons/widgets/source/images/placeholders/**cq-ul-placeholder.png**
/apps/acs-commons/widgets/source/images/placeholders/**cq-ad-placeholder.png**

If you kindly advise how to get rid of this issues it will be a great help as we are newly moving to AEM as a Cloud Service.

**Comment by davidjgonzalez** [comment]
Fixed in 5.3.2

**Comment by SearchFoundation2022** [comment]
Unfortunately the issue still exists. After upgrading the version to 5.3.2 pipeline giving the same error as provided earlier.

Also build and unit test job failed with below error and pipeline failed: 

10:48:43,364 [main] [ERROR] The following artifacts could not be resolved: biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4, biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-content-package:content-package:3.0.4, com.adobe.acs:acs-aem-commons-ui.apps:content-package:5.3.2: Could not find artifact biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4 in central (https://repo.maven.apache.org/maven2)

10:48:43,384 [main] [WARNING] The following artifacts could not be resolved: biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4, biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-content-package:content-package:3.0.4, com.adobe.acs:acs-aem-commons-ui.apps:content-package:5.3.2: Could not find artifact biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4 in central (https://repo.maven.apache.org/maven2)

could you kindly have look into it.

 Regards

**Comment by SearchFoundation2022** [comment]
Is there any update regarding the acs-aem-commons **ClientlibProxyResourceerrors** in ? 

/apps/acs-commons/widgets/themes/default/source/audio.png
/apps/acs-commons/widgets/source/images/placeholders/cq-dl-placeholder.png
/apps/acs-commons/widgets/source/images/placeholders/cq-textlines-placeholder.png
/apps/acs-commons/widgets/source/images/placeholders/cq-audio-placeholder.png
/apps/acs-commons/widgets/source/images/placeholders/cq-ul-placeholder.png
/apps/acs-commons/widgets/source/images/placeholders/cq-ad-placeholder.png

Below error has been fixed after upgrading the SDK version and build ran successfully :

10:48:43,364 [main] [ERROR] The following artifacts could not be resolved: biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4, biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-content-package:content-package:3.0.4, com.adobe.acs:acs-aem-commons-ui.apps:content-package:5.3.2: Could not find artifact biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4 in central (https://repo.maven.apache.org/maven2)

10:48:43,384 [main] [WARNING] The following artifacts could not be resolved: biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4, biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-content-package:content-package:3.0.4, com.adobe.acs:acs-aem-commons-ui.apps:content-package:5.3.2: Could not find artifact biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4 in central (https://repo.maven.apache.org/maven2)
