### ISSUE TITLE
ACS Commons - Issue Failing for copy content sync with Large Volume

### ISSUE THREAD

**Issue by jatankumar-git** [Adobe-Consulting-Services/acs-aem-commons#3555]
l. We have acs commons version upgraded to latest 6.10.0 and implemented the required setup to make it work.

We are trying to copy content from source to target environment, It works fine for smaller sub set path or pages 1-2k but if we provide a parent level path like 4k 5k pages it throws an service outage error. We were not able to see any errors and tried multiple times without any active deployment still the issue persists.

We could not find any specific details in documentations/blogs to triage the issue or if any limitation for number of pages that can be copied as such. Please look into the issue to identify what is causing this issue.

Adding screenshots for more details.

![Image](https://github.com/user-attachments/assets/ec8ece5a-bd35-4329-8388-21c11ffb252e)

Steps to reproduce- 
Select flags as recursive, incremental (Dry run enabled/disabled) and submit the job, after 3-4 mins we get an service outage error.

Similarly we tried smaller paths it worked and other locale/parent path it fails. We raised a adobe support ticket and they routed us to get a issue raised here as its related to ACS-aem-commons. 

Thanks,
Jatan

**Comment by YegorKozlov** [comment]
What are the source and target AEM instances? Are you sync-ing an AEM Cloud from another AEM cloud instance?

I seems to be a kind of a Timeout error. The target AEM instances makes a call to the source to fetch the list of page to sync. This can take time on large content trees, but I've never seen the error you are getting.

**Comment by YegorKozlov** [comment]
I think I know what's the problem is.

AEM Cloud has the default read timeout of 60 seconds. This means a request will be aborted if it didn't read at least a byte from the socket within 60 seconds. It applies to any servlet in AEM Cloud not responding for longer than 60 sec.  

I theory you can bump it up in the Jetty OSGi config, but I don't recommend it and Adobe wouldn't welcome this change either. 

My plan is to change the mechanics of getting the delta to sync from a request/response to an async job and then poll for completion. 

So instead of sending the http request to the remote AEM instance and waiting for response (which fails after 60 sec) I'm going to change Content Sync to 

 - send http request to the remote instance to create a background job to create the delta
 - poll every N seconds and print status. The socket will read these messages and keep the connection

It's a good catch and it's going to be a good improvement.

**Comment by jatankumar-git** [comment]
Yes, we are syncing from one AEM cloud to another in same program between our non prod environments. 

Thanks for the explanation for timeout issue and that seems to be the case here. Regarding technical enhancements could you please suggest how can I track them to understand possible ETA - will it be conveyed here in same ticket or we not to track with some different ticket/release notes. 

Thanks for your help and support on this issue.

**Comment by kwin** [comment]
@YegorKozlov Feel free to have a look at https://github.com/Netcentric/accesscontroltool/issues/801 which is a similar issue. I solved this with https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events. Note that the timeout is coming from Fastly (CDN) not from Web server or Jetty in this case!

**Comment by YegorKozlov** [comment]
@kwin thanks for the pointer! I'll give it a try.

@jatankumar-git Any updates will be posted on this thread. I can't give you an ETA at this point .

**Comment by simontunnat** [comment]
We are getting the same error and where also unable to find any error message.
A solution would be really great as the Cloud manager copy content functionality is absurdly slow.

**Comment by YegorKozlov** [comment]
fixed in v6.12

**Comment by YegorKozlov** [comment]
@simontunnat are using the latest  v6.12? It should be installed on both instances. The fix worked for me.

**Comment by simontunnat** [comment]
Yes I do. It took some time to get into production, but the issue still exists. If it works for others, I will invest some time next week into analyzing the root cause. Maybe it's something completely different.

Something else: Deletion of non existent resources on the target instance triggers an error. Does still work for anyone?

**Comment by YegorKozlov** [comment]
What error does it print when deleting resources?

**Comment by simontunnat** [comment]
I get the following error message:
![Image](https://github.com/user-attachments/assets/47fb1bd5-1b11-41ed-92a8-d010c20b2456)

Both environments are AEMaaCS environments and are using the latest ACS commons version 6.12.

**Comment by YegorKozlov** [comment]
@simontunnat I was able to reproduce the "Delete resources" error, opened https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3582 to track the fix

**Comment by simontunnat** [comment]
> [@simontunnat](https://github.com/simontunnat) I was able to reproduce the "Delete resources" error, opened [#3582](https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3582) to track the fix

Thank you for that.

I'm still looking into the issue where it still fails for large sites.
The response looks like this:
![Image](https://github.com/user-attachments/assets/616bfc3a-9d13-4870-8007-b4345d43d7b2)

Could not find any useful error messages jet.

Is there anyway to get debug messages or something for the request to `sync.html`?

**Comment by simontunnat** [comment]
I don't get any `sync.catalog.json` requests for the paths which fails (e.g. /content/mysite/europe).
I could see those requests for the smaller content trees.

So the process fails before it even starts to request the data from the source instance.
Any idea on how to debug this?

**Comment by simontunnat** [comment]
This is strange!

The sync started at **07:53:42**.
The request failed at **07:54:46** (after around 60 seconds):
![Image](https://github.com/user-attachments/assets/492532dd-7ecf-460a-87f7-a0d83c474847)

The first request to `sync.catalog.json` on the source instance was logged at **07:53:42** and there where TWO requests with the `root` parameter:
```
{"timestamp":"2025-05-27T07:53:42+0000","ttfb":20,"ttlb":20,"cli_ip":"20.113.98.173","cli_country":"DE","cli_region":"DE-HE","rid":"xxx","req_ua":"Apache-HttpClient/4.5.13 (Java/21.0.6)","aem_envKind":"SKYLINE","aem_tenant":"xxx","host":"author-pxxx-exxx.adobeaemcloud.com","url":"/apps/acs-commons/content/contentsync/jcr:content/sync.catalog.json?root=%2Fcontent%2Fmysite%2Feurope&strategy=com.adobe.acs.commons.contentsync.impl.LastModifiedStrategy&recursive=true","method":"GET","res_ctype":"","cache":"PASS","debug":"","res_age":"","status":401,"pop":"FRA","rules":"","alerts":"","sample":"","ddos":false}
{"timestamp":"2025-05-27T07:53:42+0000","ttfb":81,"ttlb":81,"cli_ip":"20.113.98.173","cli_country":"DE","cli_region":"DE-HE","rid":"xxx","req_ua":"Apache-HttpClient/4.5.13 (Java/21.0.6)","aem_envKind":"SKYLINE","aem_tenant":"xxx","host":"author-pxxx-exxx.adobeaemcloud.com","url":"/apps/acs-commons/content/contentsync/jcr:content/sync.catalog.json?root=%2Fcontent%2Fmysite%2Feurope&strategy=com.adobe.acs.commons.contentsync.impl.LastModifiedStrategy&recursive=true","method":"GET","res_ctype":"application/json","cache":"PASS","debug":"","res_age":"","status":200,"pop":"FRA","rules":"","alerts":"","sample":"","ddos":false}
```
(I anonymized our customer name, etc)

After this I saw logs on the target instance about resources being actually imported:
```
(WIP)
``

**Comment by YegorKozlov** [comment]
@anianweber  I created #3623 to track the changes. I suspect its a subtle regression caused by the original fix to prevent timeout errors. Previously, the operation was synchronous and the tool built the incremental delta using user credentials in the configuration. I turned it into a Sling Job which uses a service user, and there can be subtle differences.  I see you are sync-ing DAM, and `/content/dam/collections` can contain IMS folders readable by owners only, and the tool will fail sync-ing those unless the sync user is an admin. It's just my guess.
I'm going to improve error handling to log exceptions and continue to the next resource. Also, previously the audit log was saved on success only. I moved it into a `finally` block . This way you should be able to see the errors . 

@simontunnat I do have plans to refactor the code and turn JSP into a Sling Job. It's a heavy maneuver though and will take some time. I need to focus on the ongoing projects these days.
